# https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions
name: 'Maintain One Comment'
description: 'Maintain just one comment in Issue and PR.'
author: 'xrkffgg'

branding:
  # https://actions-cool.github.io/github-action-branding/
  icon: 'message-circle'
  color: 'green'

inputs:
  token:
    description: Secret GitHub API token to use for making API requests.
    default: ${{ github.token }}
    required: true
  body:
    description: Comment content.
  emojis:
    description: Add emojis to comment.
  number:
    description: Manually control the issue or PR number
  update-mode:
    description: Update comment mode. Default replace. Option append.
  comment-auth:
    description: Comment auth filter.
  body-include:
    description: Comment body filter.
  delete:
    description: Will delete all comments

outputs:
  comment-id:
    description: 'Create or update comment ID'

runs:
  using: 'node16'
  main: 'dist/index.js'
